Morak-Team/Backend

.github/workflows/cicd.yml
Dockerfile
docker-compose.yml

- close #6
- cicd worksflow 작성
- docker 관련 파일 추가
-
-

cicd workflow 작성

---

.github/workflows/cicd.yml
.gitignore
build.gradle
src/main/resources/application-datasource.properties
src/main/resources/application-local.properties
src/main/resources/application-prod.properties
src/main/resources/application-test.properties
src/main/resources/application.properties
src/test/java/com/example/seoulpublicdata2025backend/SeoulPublicData2025BackendApplicationTests.java

- close #4
- properties 세분화 어떤지?
- 환경 변수 추가도 해줘야 함.
- .env 파일을 만들어서 관리 or 인텔리제이에서 환경 변수 설정
-

chore: jpa 추가 및 properties 파일 세분화

---

src/main/java/com/example/seoulpublicdata2025backend/domain/kakaoSocialLogin/entity/Member.java
src/main/resources/application.properties
src/test/java/com/example/seoulpublicdata2025backend/domain/kakaoSocialLogin/service/MemberServiceTest.java

[Refactor] member 테이블명, 필드명 수정

---

build.gradle
src/main/java/com/example/seoulpublicdata2025backend/domain/kakaoSocialLogin/controller/KakaoAuthController.java
src/main/java/com/example/seoulpublicdata2025backend/domain/kakaoSocialLogin/controller/MemberController.java
src/main/java/com/example/seoulpublicdata2025backend/domain/kakaoSocialLogin/dto/SignupRequestDto.java
src/main/java/com/example/seoulpublicdata2025backend/domain/kakaoSocialLogin/dto/SignupResponseDto.java
src/main/java/com/example/seoulpublicdata2025backend/domain/kakaoSocialLogin/service/KakaoServiceImpl.java
src/main/java/com/example/seoulpublicdata2025backend/domain/kakaoSocialLogin/service/MemberService.java
src/main/java/com/example/seoulpublicdata2025backend/domain/kakaoSocialLogin/service/MemberServiceImpl.java
src/main/java/com/example/seoulpublicdata2025backend/domain/kakaoSocialLogin/type/MemberStatus.java
src/main/java/com/example/seoulpublicdata2025backend/global/exception/ErrorResponse.java
src/main/java/com/example/seoulpublicdata2025backend/global/exception/GlobalExceptionHandler.java
src/main/java/com/example/seoulpublicdata2025backend/global/exception/customException/AuthenticationException.java
src/main/java/com/example/seoulpublicdata2025backend/global/exception/customException/CustomException.java
src/main/java/com/example/seoulpublicdata2025backend/global/exception/customException/DuplicationMemberException.java
src/main/java/com/example/seoulpublicdata2025backend/global/exception/customException/KakaoApiException.java
src/main/java/com/example/seoulpublicdata2025backend/global/exception/errorCode/ErrorCode.java
src/main/java/com/example/seoulpublicdata2025backend/global/swagger/annotations/member/KakaoLoginCheckDocs.java
src/main/java/com/example/seoulpublicdata2025backend/global/swagger/annotations/member/SignUpDocs.java
src/main/resources/application-test.properties
src/main/resources/application.properties
src/test/java/com/example/seoulpublicdata2025backend/domain/kakaoSocialLogin/controller/MemberControllerTest.java
src/test/java/com/example/seoulpublicdata2025backend/domain/kakaoSocialLogin/service/MemberServiceTest.java

[Test] test error 수정

---

src/main/java/com/example/seoulpublicdata2025backend/domain/geocoding/entity/Company.java

- close #37 
- CompantCategoey의 EnumType을 Enumerated(EnumType.STRING)으로 수정했습니다.
-
-

[Fix] CompantCategoey의 EnumType 수정

---

src/main/java/com/example/seoulpublicdata2025backend/domain/aws/Service/AwsServiceImpl.java

- close #43 
- ErrorCode 을 잘못 사용하여 이를 수정합니다.
-
-

[!HOTFIX] ErrorCode 이름 수정

---

src/main/resources/application-test.properties

[Test] 테스트 통과되게 수정

---

src/main/java/com/example/seoulpublicdata2025backend/domain/aws/Service/AwsServiceImpl.java
src/main/java/com/example/seoulpublicdata2025backend/domain/aws/controller/AwsController.java
src/main/java/com/example/seoulpublicdata2025backend/domain/aws/dto/PresignedUrlRequestDto.java
src/main/java/com/example/seoulpublicdata2025backend/domain/kakaoSocialLogin/dto/SignupRequestDto.java
src/main/java/com/example/seoulpublicdata2025backend/domain/kakaoSocialLogin/service/MemberServiceImpl.java
src/main/java/com/example/seoulpublicdata2025backend/global/exception/errorCode/ErrorCode.java
src/main/java/com/example/seoulpublicdata2025backend/global/swagger/annotations/aws/PresignedUrlDocs.java
src/main/java/com/example/seoulpublicdata2025backend/global/swagger/annotations/member/KakaoLoginCheckDocs.java
src/main/java/com/example/seoulpublicdata2025backend/global/swagger/annotations/member/SignUpDocs.java

- close #56 
- 카카오 로그인. 회원가입, aws PreSignedUrl 관련 swagger 작성했습니다.
- SecurityUtil 사용해서 불필요하게 kakaoId 을 추가로 받는 로직은 수정했습니다.
-
-

[Docs] Swagger 적용

---

src/main/java/com/example/seoulpublicdata2025backend/global/auth/springsecurity/JwtAuthenticationFilter.java

- close #61 
- jwtFilter 에서 accessToken => access 를 찾도록 변경하였습니다.
-
-

[Fix] 쿠키에 저장된 토큰 이름 변경

---

src/main/resources/application-test.properties

- close #63 
- 테스트 환경변수를 추가했습니다.
-
-

[Test] 환경변수 추가

---

src/main/java/com/example/seoulpublicdata2025backend/domain/kakaoSocialLogin/controller/KakaoAuthController.java

- close #79 
- cookie secure 값 true로 변경
-
-

[Feat] cookie secure 값 true로 변경

---

src/main/java/com/example/seoulpublicdata2025backend/domain/kakaoSocialLogin/controller/KakaoAuthController.java
src/main/java/com/example/seoulpublicdata2025backend/global/auth/config/WebConfig.java

- close #85 
- 프론트 도메인을 "morak.site" 으로 수정하였습니다.
- CORS 설정에도 추가해주었습니다.
-
-

[Refactor] 프론트 주소 변경

---

src/main/java/com/example/seoulpublicdata2025backend/global/auth/config/WebConfig.java

- close #87 
- CORS 에 morak.site, www.morak.site 추가
-
-

[Feat] CORS 주소 추가

---

src/main/java/com/example/seoulpublicdata2025backend/global/auth/config/SecurityConfig.java

[Feat] security optional 메서드 모두 허용

---

src/main/java/com/example/seoulpublicdata2025backend/global/auth/config/WebConfig.java

[Feat] api.morak.site 도 허용

---

src/main/java/com/example/seoulpublicdata2025backend/global/auth/config/SecurityConfig.java
src/main/java/com/example/seoulpublicdata2025backend/global/auth/config/WebConfig.java
src/main/java/com/example/seoulpublicdata2025backend/global/auth/springsecurity/JwtAuthenticationFilter.java

[Feat] SecurityConfig, JwtAuthenticationFilter 수정

---

src/main/java/com/example/seoulpublicdata2025backend/global/auth/config/SecurityConfig.java

[Feat] hasRole 수정

---

src/main/java/com/example/seoulpublicdata2025backend/domain/kakaoSocialLogin/type/MemberStatus.java

- close #95 
- MemberStatus 이름을 아래와 같이 변경합니다.
```java
@Getter
@RequiredArgsConstructor
public enum MemberStatus {
MEMBER("MEMBER"),
PRE_MEMBER("PRE_MEMBER"),
NOT_MEMBER("NOT_MEMBER");
private final String value;
}
```
-
-

[Fix] 권한 이름 수정

---

src/main/java/com/example/seoulpublicdata2025backend/domain/kakaoSocialLogin/dto/SignupRequestDto.java
src/main/java/com/example/seoulpublicdata2025backend/domain/kakaoSocialLogin/entity/Member.java
src/main/java/com/example/seoulpublicdata2025backend/domain/kakaoSocialLogin/service/MemberServiceImpl.java

- close #97 
```java
@Override
public SignupResponseDto updateMember(SignupRequestDto dto) {
Long kakaoId = SecurityUtil.getCurrentMemberKakaoId();
Member findMember = memberRepository.findByKakaoId(kakaoId).orElseThrow(
() -> new NotFoundMemberException(ErrorCode.MEMBER_NOT_FOUND));
findMember.update(dto);
return SignupResponseDto.from(kakaoId);
}
```
- 기존 코드에서는 트랜잭션이 적용되지 않아 `findMember.update(dto)`을 수행해도 변경 감지가 되지 않아 DB에 업데이트가 되지 않았습니다.
- 따라서 아래와 같이 `@Transactional` 을 추가하여 변경 감지가 가능하게 변경합니다.
```java
@Override
@Transactional
public SignupResponseDto updateMember(SignupRequestDto dto) {
Long kakaoId = SecurityUtil.getCurrentMemberKakaoId();
Member findMember = memberRepository.findByKakaoId(kakaoId).orElseThrow(
() -> new NotFoundMemberException(ErrorCode.MEMBER_NOT_FOUND)); …
```

[Fix] update 메서드에 트랜잭션 적용

---

build.gradle
src/main/java/com/example/seoulpublicdata2025backend/domain/naverReceipt/component/NaverOcrClient.java
src/main/java/com/example/seoulpublicdata2025backend/domain/naverReceipt/component/NaverReceiptParser.java
src/main/java/com/example/seoulpublicdata2025backend/domain/naverReceipt/controller/NaverReceiptController.java
src/main/java/com/example/seoulpublicdata2025backend/domain/naverReceipt/dto/ReceiptInfoDto.java
src/main/java/com/example/seoulpublicdata2025backend/domain/naverReceipt/dto/ReceiptInfoResponseDto.java
src/main/java/com/example/seoulpublicdata2025backend/domain/naverReceipt/service/NaverReceiptServiceImpl.java
src/main/java/com/example/seoulpublicdata2025backend/global/exception/GlobalExceptionHandler.java
src/main/java/com/example/seoulpublicdata2025backend/global/exception/customException/NaverOcrException.java
src/main/java/com/example/seoulpublicdata2025backend/global/exception/errorCode/ErrorCode.java
src/main/java/com/example/seoulpublicdata2025backend/global/swagger/annotations/naverReceipt/NaverReceiptDocs.java
src/main/resources/application.properties

- close #114 
- 클라이언트에서 영수증 리뷰를 할 때 주문 목록은 필요로 하지 않으므로 이 정보를 반환하지 않습니다.
- 기업 주소와 영수증 주소를 비교할 때 유사도 검사를 도입하여 80% 이상의 유사도를 가질 때만 유효하다고 판단합니다. (`org.apache.commons:commons-text:1.13.1`) 을 사용했습니다.
```java
private boolean isNotSameCompany(CompanyLocationTypeDto companyDto, ReceiptInfoDto receiptInfoDto) {
String companyLocation = companyDto.getCompanyLocation();
String companyAddress = receiptInfoDto.getStoreAddress();
LevenshteinDistance levenshtein = new LevenshteinDistance(null);
String normalizedCompanyLocation = normalize(companyLocation);
String normalizedCompanyAddress = normalize(companyAddress);
int distance = levenshtein.apply(normalizedCompanyLocation, normalizedCompanyAddress);
int maxLen = Math.max(normalizedCompanyLocation.length(), normalizedCompanyAddress.length());
if (maxLen …
```

[Fix] 영수증 반환값 수정, 기업 주소 비교에 유사도 검사 도입

---

src/main/java/com/example/seoulpublicdata2025backend/domain/review/controller/ReviewController.java
src/test/java/com/example/seoulpublicdata2025backend/domain/company/service/CompanyServiceImplTest.java
src/test/java/com/example/seoulpublicdata2025backend/domain/company/service/MemberCompanySaveServiceImplTest.java
src/test/java/com/example/seoulpublicdata2025backend/domain/review/controller/ReviewControllerTest.java

- close #125 
- 미처 확인하지 못한 테스트 코드를 통과하게 수정합니다. 
- 기존 예외가 아닌 커스텀 예외를 반환하게 합니다.
-
-

[Test] 테스트 코드 수정

---

src/main/java/com/example/seoulpublicdata2025backend/domain/naverReceipt/component/NaverReceiptParser.java
src/main/java/com/example/seoulpublicdata2025backend/domain/naverReceipt/dto/ReceiptInfoDto.java
src/main/java/com/example/seoulpublicdata2025backend/domain/naverReceipt/dto/ReceiptInfoResponseDto.java
src/main/java/com/example/seoulpublicdata2025backend/global/swagger/annotations/naverReceipt/NaverReceiptDocs.java

- close #129 
- 프론트에서 승인번호를 필요함에 따라 반환값에 승인번호값을 추가합니다.
- 만약 승인번호를 인식하지 못하면, null 값을 전달합니다.
-
-

[Feat] 영수증 반환값에 승인번호를 추가합니다.

---

src/main/java/com/example/seoulpublicdata2025backend/domain/member/controller/MemberController.java
src/main/java/com/example/seoulpublicdata2025backend/global/swagger/annotations/member/LogoutDocs.java

- close #133 
- 로그아웃 요청을 하면 단순히 프론트의 쿠키 내에 access 라는 키에 해당하는 값을 "" (빈 문자열)로 바꿔줍니다.
- access token이 없어졌기에 다시 로그인을 해서 새로운 access token을 발급받게 합니다.
-
-

[Feat] 로그아웃 기능 추가

---

src/main/java/com/example/seoulpublicdata2025backend/domain/company/dao/CompanyRepository.java
src/main/java/com/example/seoulpublicdata2025backend/domain/company/dto/CompanyLocationTypeDto.java
src/main/java/com/example/seoulpublicdata2025backend/domain/naverReceipt/dto/ReceiptInfoDto.java
src/main/java/com/example/seoulpublicdata2025backend/domain/naverReceipt/dto/ReceiptInfoResponseDto.java
src/main/java/com/example/seoulpublicdata2025backend/global/swagger/annotations/naverReceipt/NaverReceiptDocs.java
src/test/java/com/example/seoulpublicdata2025backend/domain/member/service/MemberConsumptionServiceImplTest.java

- close #138 
- 영수증 리뷰 결과 반환 시 기업의 카테고리도 반환하게 추가하였습니다.
-
-

[Feat] 영수증 반환 값에 기업 카테고리 추가

---

src/main/java/com/example/seoulpublicdata2025backend/domain/review/controller/ReviewController.java

- close #
- 누락된 유효성 검사를 추가합니다.
-
-

[Fix] 누락된 유효성 검사 추가

---

src/test/java/com/example/seoulpublicdata2025backend/domain/member/controller/MemberControllerTests.java

[Test] 테스트 삭제

---

src/main/java/com/example/seoulpublicdata2025backend/domain/review/dao/CompanyReviewRepository.java
src/main/java/com/example/seoulpublicdata2025backend/global/swagger/annotations/member/GetMeberConsumptionDetailDocs.java

- close #168 
- repository 에서 jpql을 만들때 파라미터 이름이 잘못되어 500 예외가 발생하던 문제를 수정합니다.
```java
@Query("SELECT COUNT(*) FROM CompanyReview cr "
+ "WHERE cr.kakaoId = :kakaoId AND cr.company.companyType = :companyType")
Long getCountByKakaoIdAndCompanyType(Long companyId, CompanyType companyType); // => companyId를 kakaoId로 수정합니다
```
-
-

[Fix] repository jpql 파라미터 이름 수정

---

src/main/java/com/example/seoulpublicdata2025backend/domain/review/dao/CompanyReviewRepository.java

- close #179 
- jpql 을 객체 중심으로 다시 작성했습니다. 괜히 줄일려다가 피해본거같습니다.
-
-

[Fix] jpql 객체 모델을 중심으로 다시 작성

---

src/main/java/com/example/seoulpublicdata2025backend/domain/support/dto/ConsumerSupportProductResponseDetailDto.java
src/main/java/com/example/seoulpublicdata2025backend/domain/support/entity/ConsumerSupportProduct.java
src/main/java/com/example/seoulpublicdata2025backend/domain/support/service/ConsumerSupportProductServiceImpl.java

- close #181
- 엑셀 파일이 변경됨에 따라 2개의 필드를 추가했습니다. (method, period)
-
-

[Fix] entity 필드를 추가합니다.

---

src/main/java/com/example/seoulpublicdata2025backend/global/auth/config/SecurityConfig.java

- close #191 
- CORS 허용 URL 추가
-
-

[Feat] CORS 허용 URL 추가

---

src/main/java/com/example/seoulpublicdata2025backend/domain/naverReceipt/dto/ReceiptInfoResponseDto.java
src/main/java/com/example/seoulpublicdata2025backend/domain/review/service/ReviewServiceImpl.java
src/main/java/com/example/seoulpublicdata2025backend/global/exception/GlobalExceptionHandler.java
src/main/java/com/example/seoulpublicdata2025backend/global/exception/errorCode/ErrorCode.java

- close #199 
- 중복 데이터 저장 시 500 예외를 발생하지 않게 처리했습니다.
- 영수증 반환값을 수정하였습니다.
-
-

[Fix] 409 에러 반환 및 영수증 반환 값 수정

---

src/main/java/com/example/seoulpublicdata2025backend/domain/naverReceipt/service/NaverReceiptServiceImpl.java

- close #210 
- 기존 유사도를 70 -> 50으로 낮추었습니다.
-
-

[Fix] 유사도 50으로 수정
